#!/bin/bash

protected_branch='master'
current_branch=$(git symbolic-ref --short HEAD)

if [ $protected_branch = $current_branch ]
then
  echo 'Pushing directly to master is forbidden'
  exit 1 # prevent push
else
  exit 0 # push will execute
fi
